In [189]:
import pandas as pd 
import numpy as np

In [190]:
df = pd.read_csv("dataset/NSL_KDD_Train.csv")
df

,0,tcp,ftp_data,SF,491,0.1,0.2,0.3,0.4,0.5,...,25,0.17,0.03,0.17.1,0.25,0.26,0.27,0.05,0.28,normal
0,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
1,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
2,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
3,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
4,0,tcp,private,REJ,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,0,tcp,private,S0,0,0,0,0,0,0,...,25,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125968,8,udp,private,SF,105,145,0,0,0,0,...,244,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,normal
125969,0,tcp,smtp,SF,2231,384,0,0,0,0,...,30,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,normal
125970,0,tcp,klogin,S0,0,0,0,0,0,0,...,8,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125971,0,tcp,ftp_data,SF,151,0,0,0,0,0,...,77,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,normal

In [191]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125972 entries, 0 to 125971
Data columns (total 42 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   0         125972 non-null  int64
 1   tcp       125972 non-null  object
 2   ftp_data  125972 non-null  object
 3   SF        125972 non-null  object
 4   491       125972 non-null  int64
 5   0.1       125972 non-null  int64
 6   0.2       125972 non-null  int64
 7   0.3       125972 non-null  int64
 8   0.4       125972 non-null  int64
 9   0.5       125972 non-null  int64
 10  0.6       125972 non-null  int64
 11  0.7       125972 non-null  int64
 12  0.8       125972 non-null  int64
 13  0.9       125972 non-null  int64
 14  0.10      125972 non-null  int64
 15  0.11      125972 non-null  int64
 16  0.12      125972 non-null  int64
 17  0.13      125972 non-null  int64
 18  0.14      125972 non-null  int64
 19  0.15      125972 non-null  int64
 20  0.16      125972 non-null  int64
 21  0.18      125972 non-null  int64
 22  2         125972 non-null  int64
 23  2.1       125972 non-null  int64
 24  0.19      125972 non-null  float64
 25  0.20      125972 non-null  float64
 26  0.21      125972 non-null  float64
 27  0.22      125972 non-null  float64
 28  1         125972 non-null  float64
 29  0.23      125972 non-null  float64
 30  0.24      125972 non-null  float64
 31  150       125972 non-null  int64
 32  25        125972 non-null  int64
 33  0.17      125972 non-null  float64
 34  0.03      125972 non-null  float64
 35  0.17.1    125972 non-null  float64
 36  0.25      125972 non-null  float64
 37  0.26      125972 non-null  float64
 38  0.27      125972 non-null  float64
 39  0.05      125972 non-null  float64
 40  0.28      125972 non-null  float64
 41  normal    125972 non-null  object
dtypes: float64(15), int64(23), object(4)
memory usage: 40.4+ MB

In [192]:
df.isnull().sum()

0           0
tcp         0
ftp_data    0
SF          0
491         0
0.1         0
0.2         0
0.3         0
0.4         0
0.5         0
0.6         0
0.7         0
0.8         0
0.9         0
0.10        0
0.11        0
0.12        0
0.13        0
0.14        0
0.15        0
0.16        0
0.18        0
2           0
2.1         0
0.19        0
0.20        0
0.21        0
0.22        0
1           0
0.23        0
0.24        0
150         0
25          0
0.17        0
0.03        0
0.17.1      0
0.25        0
0.26        0
0.27        0
0.05        0
0.28        0
normal      0
dtype: int64

In [193]:
df.describe()

,0,491,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,150,25,0.17,0.03,0.17.1,0.25,0.26,0.27,0.05,0.28
count,125972.000000,1.259720e+05,1.259720e+05,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,...,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000
mean,287.146929,4.556710e+04,1.977927e+04,0.000198,0.022688,0.000111,0.204411,0.001222,0.395739,0.279253,...,182.149200,115.653725,0.521244,0.082952,0.148379,0.032543,0.284455,0.278487,0.118832,0.120241
std,2604.525522,5.870354e+06,4.021285e+06,0.014086,0.253531,0.014366,2.149977,0.045239,0.489011,23.942137,...,99.206565,110.702886,0.448950,0.188922,0.308998,0.112564,0.444785,0.445670,0.306559,0.319460
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,82.000000,10.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,4.400000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,255.000000,63.000000,0.510000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,2.760000e+02,5.160000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,255.000000,255.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000
max,42908.000000,1.379964e+09,1.309937e+09,1.000000,3.000000,3.000000,77.000000,5.000000,1.000000,7479.000000,...,255.000000,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

#### Renaming Of Columns

In [194]:
# df.rename(columns={'normal':'attacks' , 'tcp':'protocol_type' , 'ftp_data':'service' , 'SF':'flag'} , inplace=True)
# df

In [195]:
column_names = [
    "duration",
    "protocol_type",
    "service",
    "flag",
    "src_bytes",
    "dst_bytes",
    "land",
    "wrong_fragment",
    "urgent",
    "hot",
    "num_failed_logins",
    "logged_in",
    "num_compromised",
    "root_shell",
    "su_attempted",
    "num_root",
    "num_file_creations",
    "num_shells",
    "num_access_files",
    "num_outbound_cmds",
    "is_host_login",
    "is_guest_login",
    "count",
    "srv_count",
    "serror_rate",
    "srv_serror_rate",
    "rerror_rate",
    "srv_rerror_rate",
    "same_srv_rate",
    "diff_srv_rate",
    "srv_diff_host_rate",
    "dst_host_count",
    "dst_host_srv_count",
    "dst_host_same_srv_rate",
    "dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate",
    "dst_host_serror_rate",
    "dst_host_srv_serror_rate",
    "dst_host_rerror_rate",
    "dst_host_srv_rerror_rate",
    "attack"
]

# Assign column names
df.columns = column_names

In [196]:
df.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'attack'],
      dtype='object')

In [197]:
df['attack'].value_counts()

attack
normal             67342
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: count, dtype: int64

In [198]:
df.drop(columns= 'duration' , inplace=True)

In [199]:
df

,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack
0,udp,other,SF,146,0,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
1,tcp,private,S0,0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
2,tcp,http,SF,232,8153,0,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
3,tcp,http,SF,199,420,0,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
4,tcp,private,REJ,0,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,tcp,private,S0,0,0,0,0,0,0,0,...,25,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125968,udp,private,SF,105,145,0,0,0,0,0,...,244,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,normal
125969,tcp,smtp,SF,2231,384,0,0,0,0,0,...,30,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,normal
125970,tcp,klogin,S0,0,0,0,0,0,0,0,...,8,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125971,tcp,ftp_data,SF,151,0,0,0,0,0,0,...,77,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,normal

#### Encoding Of Columns

In [200]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

In [201]:
le = LabelEncoder()
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [202]:
columns_encoded = df[['protocol_type', 'service', 'flag']]
columns_encoded_columns = ['protocol_type', 'service', 'flag']
columns_encoded

       protocol_type   service flag
0                udp     other   SF
1                tcp   private   S0
2                tcp      http   SF
3                tcp      http   SF
4                tcp   private  REJ
...              ...       ...  ...
125967           tcp   private   S0
125968           udp   private   SF
125969           tcp      smtp   SF
125970           tcp    klogin   S0
125971           tcp  ftp_data   SF

[125972 rows x 3 columns]

In [203]:
columns_encoded = ohe.fit_transform(columns_encoded)

In [204]:
columns_encoded = pd.DataFrame(columns_encoded , columns=ohe.get_feature_names_out(columns_encoded_columns))
columns_encoded

,protocol_type_icmp,protocol_type_tcp,protocol_type_udp,service_IRC,service_X11,service_Z39_50,service_aol,service_auth,service_bgp,service_courier,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
125968,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
125969,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
125970,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
125971,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [205]:
df['attack'].value_counts()

attack
normal             67342
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: count, dtype: int64

In [206]:
df['attack']

0          normal
1         neptune
2          normal
3          normal
4         neptune
           ...
125967    neptune
125968     normal
125969     normal
125970    neptune
125971     normal
Name: attack, Length: 125972, dtype: object

In [207]:
df['attack'] = df['attack'].apply(lambda x: 0 if x == 'normal' else 1)
df['attack'].value_counts()

attack
0    67342
1    58630
Name: count, dtype: int64

In [208]:
df.drop(columns=['protocol_type', 'service', 'flag'] , inplace=True)

In [209]:
df

,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack
0,146,0,0,0,0,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,0
1,0,0,0,0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,1
2,232,8153,0,0,0,0,0,1,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,0
3,199,420,0,0,0,0,0,1,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
4,0,0,0,0,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.00,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,0,0,0,0,0,0,0,0,0,0,...,25,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,1
125968,105,145,0,0,0,0,0,0,0,0,...,244,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0
125969,2231,384,0,0,0,0,0,1,0,0,...,30,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,0
125970,0,0,0,0,0,0,0,0,0,0,...,8,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,1
125971,151,0,0,0,0,0,0,1,0,0,...,77,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,0

In [210]:
new_df = pd.concat([columns_encoded , df] , axis=1)

In [211]:
new_df

,protocol_type_icmp,protocol_type_tcp,protocol_type_udp,service_IRC,service_X11,service_Z39_50,service_aol,service_auth,service_bgp,service_courier,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,1
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.00,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,1
125968,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,244,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0
125969,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,30,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,0
125970,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,1
125971,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,77,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,0

In [212]:
new_df.columns

Index(['protocol_type_icmp', 'protocol_type_tcp', 'protocol_type_udp',
       'service_IRC', 'service_X11', 'service_Z39_50', 'service_aol',
       'service_auth', 'service_bgp', 'service_courier',
       ...
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'attack'],
      dtype='object', length=122)

### Scaling

In [213]:
from sklearn.preprocessing import StandardScaler

In [214]:
ss = StandardScaler()

In [215]:
# df_scaled = ss.fit_transform(new_df)
# df_scaled = pd.DataFrame(df_scaled , columns=new_df.columns)
# df_scaled

#### Model Building And Training

In [216]:
from sklearn.model_selection import train_test_split

In [217]:
x = new_df.drop(columns='attack')

# 🔥 SAVE FEATURE NAMES HERE
feature_names = x.columns.tolist()

x

,protocol_type_icmp,protocol_type_tcp,protocol_type_udp,service_IRC,service_X11,service_Z39_50,service_aol,service_auth,service_bgp,service_courier,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,19,0.07,0.07,0.00,0.00,0.00,0.00,1.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,25,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00
125968,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,244,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00
125969,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,30,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00
125970,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,8,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00
125971,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,77,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00

In [218]:
x = ss.fit_transform(x)
x

array([[-0.26543017, -2.10005685,  2.72067166, ..., -0.62487425,
        -0.38763494, -0.37638873],
       [-0.26543017,  0.47617758, -0.3675563 , ...,  1.61894633,
        -0.38763494, -0.37638873],
       [-0.26543017,  0.47617758, -0.3675563 , ..., -0.60243604,
        -0.38763494, -0.34508583],
       ...,
       [-0.26543017,  0.47617758, -0.3675563 , ..., -0.62487425,
        -0.35501463, -0.37638873],
       [-0.26543017,  0.47617758, -0.3675563 , ...,  1.61894633,
        -0.38763494, -0.37638873],
       [-0.26543017,  0.47617758, -0.3675563 , ..., -0.62487425,
        -0.38763494, -0.37638873]], shape=(125972, 121))

In [219]:
y = new_df['attack']
y.astype(int)

0         0
1         1
2         0
3         0
4         1
         ..
125967    1
125968    0
125969    0
125970    1
125971    0
Name: attack, Length: 125972, dtype: int64

In [220]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state=42)

In [221]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((100777, 121), (25195, 121), (100777,), (25195,))

#### Linear Regression Model

In [222]:
from sklearn.linear_model import LogisticRegression

In [223]:
lr = LogisticRegression()

In [224]:
type(lr)

sklearn.linear_model._logistic.LogisticRegression

In [225]:
lr.fit(x_train , y_train)

C:\Users\VICTUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [226]:
y_pred = lr.predict(x_test)

In [227]:
y_pred

array([1, 1, 0, ..., 1, 1, 1], shape=(25195,))

### Model Evaluation

In [228]:
from sklearn.metrics import confusion_matrix , f1_score , precision_score , accuracy_score , recall_score

In [229]:
confusion_matrix(y_test , y_pred)

array([[13096,   290],
       [  407, 11402]])

In [230]:
accuracy_score(y_test , y_pred)

0.9723357809089105

In [231]:
precision_score(y_test , y_pred)

0.9751967157030448

In [232]:
recall_score(y_test , y_pred)

0.9655347616224913

In [233]:
f1_score(y_test , y_pred)

0.9703416875877622

#### SVM Model

In [234]:
from sklearn.svm import SVC

In [235]:
svc = SVC( kernel='rbf',
    C=1.0,
    gamma='scale',
    class_weight='balanced' , 
    probability=True)

In [236]:
svc.fit(x_train , y_train)

SVC(class_weight='balanced', probability=True)

In [237]:
# feature_names = x_train.columns.tolist()

In [238]:
svc.predict(x_test)

array([1, 1, 0, ..., 1, 1, 1], shape=(25195,))

#### Model Evaluation

In [239]:
from sklearn.metrics import confusion_matrix , f1_score , precision_score , accuracy_score , recall_score

In [240]:
confusion_matrix(y_test , y_pred)

array([[13096,   290],
       [  407, 11402]])

In [241]:
f1_score(y_test , y_pred)

0.9703416875877622

In [242]:
precision_score(y_test , y_pred)

0.9751967157030448

In [243]:
accuracy_score(y_test , y_pred)

0.9723357809089105

In [244]:
recall_score(y_test , y_pred)

0.9655347616224913

#### Saving Files

In [245]:
import joblib

joblib.dump(svc, "svm_model.pkl")      
joblib.dump(ss, "scaler.pkl")
joblib.dump(feature_names, "feature_names.pkl")

['feature_names.pkl']

In [246]:
import joblib
import pandas as pd
import numpy as np

# Load trained model
model = joblib.load("svm_model.pkl")

# Number of features expected by the model
n_features = model.n_features_in_

# Create dummy test data (10 rows)
X_test_dummy = np.random.rand(10, n_features)

# Convert to DataFrame
df_test = pd.DataFrame(X_test_dummy)

# Save CSV
df_test.to_csv("test_network_data.csv", index=False)

print("✅ test_network_data.csv created")
print("Features:", n_features)

✅ test_network_data.csv created
Features: 121

In [252]:
label_map = {
    0: "Normal",
    1: "Attack"
}

decoded_preds = [label_map[p] for p in preds]
print(decoded_preds[:10])

['Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal']

In [256]:
import pandas as pd
import joblib

model = joblib.load("svm_model.pkl")
scaler = joblib.load("scaler.pkl")
feature_names = joblib.load("feature_names.pkl")

label_map = {0: "Normal", 1: "Attack"}

test_df = pd.read_csv("test_network_data.csv")   # use any test CSV you have

test_df = test_df.reindex(columns=feature_names, fill_value=0)

test_scaled = scaler.transform(test_df)
preds = model.predict(test_scaled)

decoded_preds = [label_map[p] for p in preds]
print(decoded_preds[:10])

['Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal']

In [249]:
print(model.classes_)

[0 1]